### ISSUE TITLE
Enable Touch support

### ISSUE THREAD

**Issue by creativenoobie** [mercs600/vue2-perfect-scrollbar#1]
Hey,

Thanks for creating a wrapper for vue2 that too with SSR support but this component do not work on mobile where Pointer is touch instead of mouse.

Please check.

Thanks!

**Comment by creativenoobie** [comment]
I just found out that it's working on my mobile but in responsive mode (Firefox as well as Chrome) for developing/debugging purposes.

**Comment by mercs600** [comment]
Hi @creativenoobie. I just checked your problem. It's not related directly with this wrapper. But I found the issue on the perfect-scrollbar github. The solution is you have to refresh the page after switch to console on "responsive" in dev tool ;-) 

https://github.com/utatti/perfect-scrollbar/issues/406

**Comment by mercs600** [comment]
@creativenoobie Is it helpful for you ? I'm closing this issue. Don't hesitate to reopen if you need more help.

**Comment by mdarifmustafa** [comment]
to make use in mobile responsiveness, we have to refresh the page to use this wrapper, very bad UX this is.
