### ISSUE TITLE
Using 2 scrollbar one of them in modal

### ISSUE THREAD

**Issue by muscle-rhnkyr** [mercs600/vue2-perfect-scrollbar#10]
Hi there,

my issues is, I use 2 scrollbar on page and one of them on bootstrap modal. when modal pops up and try to scroll by mouse wheel the scroll on main page scrolls as well. How can I prevent main page to scroll. 

Cheers.

**Comment by hfalucas** [comment]
Add `:settings="{wheelPropagation: false}"` to your modal window scroller

**Comment by muscle-rhnkyr** [comment]
@hfalucas thanks for tip

cheers.
