### ISSUE TITLE
Could not find a declaration file for module 'vue2-perfect-scrollbar'

### ISSUE THREAD

**Issue by naime-hossain** [mercs600/vue2-perfect-scrollbar#14]
module "e:/javascriptCoding/02.vue/vue/node_modules/vue2-perfect-scrollbar/dist/vue2-perfect-scrollbar.cjs"
Could not find a declaration file for module 'vue2-perfect-scrollbar'. 'e:/javascriptCoding/vue/node_modules/vue2-perfect-scrollbar/dist/vue2-perfect-scrollbar.cjs.js' implicitly has an 'any' type.
  Try `npm install @types/vue2-perfect-scrollbar` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue2-perfect-scrollbar';`

**Comment by darthf1** [comment]
This means there are no typescript definitions available. See #7

**Comment by mercs600** [comment]
@naime-hossain @darthf1 @florianrusch @schwarzdavid I added simple ts definitions to avoid these warnings.
