### ISSUE TITLE
depends on latest perfect-scrollbar ?

### ISSUE THREAD

**Issue by z3rog** [mercs600/vue2-perfect-scrollbar#15]
here's my situation: 
I'm using vue2-perfect-scrollbar in my project, but found event listeners were not binding correctly in windows devices with touch screen. I noticed that perfect-scrollbar has fixed this but no one publish the new one to npm. However, this wrapper depends on perfect-scrollbar, what should i do ? 

If I create a new repo, fork the latest perfect-scrollbar, build , and publish to npm, and do the same thing to vue2-perfect-scrollbar, do i break the license ?  @mercs600

**Comment by mercs600** [comment]
Sorry, I don't get you right first time. Generally mdbootstrap should merge these PR. I would like to support official perfect-scrollbar repository as dependnecy. 

What in case when you just use my wrapper with official dependency and replace perfect-scrollbar dependency (for your fork) in your package.json - does it make sense ?

**Comment by mercs600** [comment]
@z3rog I close this issue, my last comment should be helpful.
