### ISSUE TITLE
Installation 1.2.4 stuck on Windows

### ISSUE THREAD

**Issue by darthf1** [mercs600/vue2-perfect-scrollbar#28]
Im running `Yarn 1.19.2` with `Windows 10` and I'm unable to upgrade from `1.2.3` to `1.2.4`. The installation is stuck at:

`verbose 1.439315201 Performing "GET" request to "https://registry.yarnpkg.com/vue2-perfect-scrollbar/-/vue2-perfect-scrollbar-1.2.4.tgz".`

I'm able to install the package on `Alpine` with `Yarn`. I'm able to install the package with `NPM` on `Windows`. I already did a `yarn cache clear` and removed the `node_modules` folder. 

When comparing the two releases, I noticed the `1.2.4` release .tgz file includes a file which is just a `/`, could that be the issue?

![image](https://user-images.githubusercontent.com/17253332/70048040-a7708380-15c9-11ea-925a-f47d331bd710.png)

**Comment by darthf1** [comment]
Hi @mercs600, do you have any idea?

**Comment by mercs600** [comment]
sorry @darthf1 but I don't have idea how to reproduce it. I don't see that file what are you talking about, also when I download it as a zip. I can test it only on macOS/Linux at this moment and it works. Could you try on different PC ?

**Comment by darthf1** [comment]
Hi @mercs600, thanks for your response. I don't have another PC to test, I will try to do that later. I also have no issues on Linux (don't have a macOS), only with `Yarn` on `Windows`.

These are the files I've downloaded:
https://registry.yarnpkg.com/vue2-perfect-scrollbar/-/vue2-perfect-scrollbar-1.2.3.tgz
https://registry.yarnpkg.com/vue2-perfect-scrollbar/-/vue2-perfect-scrollbar-1.2.4.tgz

If I open these files with `Winrar` I get the result as shown in the screenshot.

@fishiky and @Jay-Bond, since you gave the initial post a thumbs up, do you have the same issue?

**Comment by darthf1** [comment]
@mercs600 just tried on a different Windows 10 PC, I have the same issue there.

**Comment by mercs600** [comment]
I see, I just published new version on npm with your typo fix. Could you check now ?

**Comment by darthf1** [comment]
Yep! Much better. Can install 1.2.5 without issues. Just a one-off glitch I guess. The weird file is gone, so I guess that led to the installation failure.

![image](https://user-images.githubusercontent.com/17253332/71130065-524f8700-21f1-11ea-8e8c-3f6d12848b91.png)

**Comment by mercs600** [comment]
Nice! yes it was weird ;-) Thanks for the information.
