### ISSUE TITLE
can possible applied in body tag?

### ISSUE THREAD

**Issue by ayophanz** [mercs600/vue2-perfect-scrollbar#30]
I want body tag to be perfect scroll

**Comment by mercs600** [comment]
@ayophanz Probably yes, but why do you want to to this ? This is not recommended options to mount application on body tag. Maybe better option will be create container which get height/width 100% of body ?

**Comment by ayophanz** [comment]
@Admin Panel <iresnef@gmail.com> My main scrollbar is on my body tag, I
think this is important.

**Comment by mercs600** [comment]
It doesn't have to be on body. You can set overflow to hidden on body and html tag - then your first div wrapper will be responsible for scrolling. Have a look at this example: 
https://codesandbox.io/s/vue-perfect-scrollbar-component-local-registration-biuhn?fontsize=14&hidenavigation=1&module=%2Fsrc%2FApp.vue&theme=dark

I have set 
```css
html,
body,
#app {
  height: 100%;
  width: 100%;
  overflow: hidden;
  margin: 0;
  padding: 0;
}
```

So first wrapper #app is equal to body height. I have set overflow: hidden also to disable native scroll. 
Then I setup `<perfect-scrollbar/>` as a wrapper component for application:

```html
<template>
  <perfect-scrollbar id="app">
    <HelloWorld/>
    <HelloWorld/>
    <HelloWorld/>
    <HelloWorld/>
    <img width="25%" src="./assets/logo.png">
  </perfect-scrollbar>
</template>
```

It should works for you.
