### ISSUE TITLE
Bug: Cannot read property 'scrollTop' of null in "updateGeometry", on some mobile devices

### ISSUE THREAD

**Issue by LucasGenoud** [mercs600/vue2-perfect-scrollbar#31]
I haven't been able to reproduce this error myself but this error got trigged in our Sentry : 

> Cannot read property 'scrollTop' of null

This seems to be occuring in this function at the third line: 

```
var updateGeometry = function(i) {
var element = i.element;
var roundedScrollTop = Math.floor(element.scrollTop);
i.containerWidth = element.clientWidth;
i.containerHeight = element.clientHeight;
i.contentWidth = element.scrollWidth;
i.contentHeight = element.scrollHeight;
```
It occurs on both IOS and Android, on chrome, firefox, safari but not consistently. 

Let me know if you want some more details

**Comment by mercs600** [comment]
Hi @LucasGenoud  thank you for the information, but you have to notice that source code what are you talking about is the source of perfect-scrollbar library. This repository is only the wrapper for vuejs component. Have a look at it -> https://github.com/mdbootstrap/perfect-scrollbar/search?q=Cannot+read+property+%27scrollTop%27+of+null&type=Issues

**Comment by LucasGenoud** [comment]
Oh my bad,
Thank you for your quick anwser !

**Comment by hmoffatt** [comment]
This has been fixed in perfect-scrollbar, but the faulty code is built in vue2-perfect-scrollbar.umd.js so there needs to be a release of vue2-perfect-scrollbar to pick up the fix.

**Comment by mercs600** [comment]
@hmoffatt do you mean some fork or pull request of perfect-scrollbar ? where it was fixed ?

**Comment by hmoffatt** [comment]
I mean it's fixed on mdbootstrap/perfect-scrollbar master now, but it hasn't been released unfortunately.
