### ISSUE TITLE
Can't scroll when hover on table overflow auto

### ISSUE THREAD

**Issue by tailuis7** [mercs600/vue2-perfect-scrollbar#36]
Vue2 perfect scroll bar can't scroll when user hover on table has style with overflow: auto
Reproduce:
https://codesandbox.io/s/vue-perfect-scrollbar-bug-on-table-responsive-4i877

**Comment by mercs600** [comment]
@tailuis7 Are you sure is it an issue related with this repository ? This is just wrapper for vue & perfect-scrollbar. Please test it with perfect-scrollbar itself.

**Comment by tailuis7** [comment]
> @tailuis7 Are you sure is it an issue related with this repository ? This is just wrapper for vue & perfect-scrollbar. Please test it with perfect-scrollbar itself.

I did test with perfect-scrollbar, same issue happened. Anyway to resolve this issue?

**Comment by mercs600** [comment]
@tailuis7 it seems to be working with upgraded version of vue2-perfect-scrollbar. I just switched to 1.5.0 -> https://codesandbox.io/s/vue-perfect-scrollbar-bug-on-table-responsive-016nt?fontsize=14&hidenavigation=1&theme=dark
