### ISSUE TITLE
Scrolling div height is not updated if I remove an item

### ISSUE THREAD

**Issue by jetlej** [mercs600/vue2-perfect-scrollbar#40]
See here: https://www.loom.com/share/b4c4e4da4cf1443fac1e9b59e348c33d

If there is an overflow, and I scroll to bottom and then delete an item, the list doesn't snap down to fill the blank. It only updates if I scroll up past where the blank space is.

**Comment by mercs600** [comment]
Is your div has setup max-height or height ? The better way is just call update method when you know that after some actions container height may be changed. 

Just setup reference 
```<perfect-scrollbar ref="scroll">```

And call update after some predicted changes 
```this.$refs.scroll.update()```

**Comment by jetlej** [comment]
That worked, thank you!
