### ISSUE TITLE
Scrollbars flash when I remove an item from list, which changes the div height

### ISSUE THREAD

**Issue by jetlej** [mercs600/vue2-perfect-scrollbar#41]
When there is no overflow, I see the scroll bars flash visible for a second when I edit a list height by deleting an item. Is there a way to avoid this?

**Comment by mercs600** [comment]
@jetlej unfortunately the overflow property is required, read more here -> https://github.com/mdbootstrap/perfect-scrollbar#before-using-perfect-scrollbar
