### ISSUE TITLE
No space between content and scrollbars

### ISSUE THREAD

**Issue by satnam9781** [mercs600/vue2-perfect-scrollbar#44]
Is there any way to add some space between the content and the scrollbars? I don't want the scrollbars to overlap my content.

**Comment by mercs600** [comment]
@satnam9781 just add some padding by CSS for wrapper responsible for content.

**Comment by mercs600** [comment]
I provided simple example - I have just added padding-right. 
https://codesandbox.io/s/vue-perfect-scrollbar-component-with-padding-6gnsv?file=/src/App.vue

**Comment by RajasekharReddy82** [comment]
@satnam9781 please add example code.
