### ISSUE TITLE
Infinite scrolling when box with border

### ISSUE THREAD

**Issue by a-dovbnya** [mercs600/vue2-perfect-scrollbar#49]
Hi! In vue2-perfect-scrollbar 1.5.0 version was found bug: if div.ps have border, then can see infinite scroll (https://codesandbox.io/s/vue-perfect-scrollbar-global-registration-p7u5p?file=/src/App.vue - https://i.imgur.com/GVjEDYe.png).

**Comment by mercs600** [comment]
@a-dovbnya thank you for report, are you able to confirm that is it issue of vue2-perfect-scrollbar - because this is only wrapper for https://github.com/mdbootstrap/perfect-scrollbar and maybe you should report this bug there.

**Comment by a-dovbnya** [comment]
Yes, it is very likely that the problem is in perfect-scrollbar. It is worth writing to them. Thank!
