### ISSUE TITLE
Vue 3 Support 

### ISSUE THREAD

**Issue by jd-0001** [mercs600/vue2-perfect-scrollbar#60]
Do this package support Vue 3? As Vue 3 has RC It will be a good idea to add support for Vue 3.

Regards.

**Comment by mercs600** [comment]
yes, the name may be confused, but it should be works with vue 3 as well.

**Comment by jd-0001** [comment]
@mercs600 Great. Thanks. Closing this. I will probably use your package from tomorrow morning and will let you know if there's any issues.

**Comment by jd-0001** [comment]
Hi @mercs600 

I have tested it in the fresh Vue 3 project and I am getting error. This is due to the render function API is changed for vue 3. Also if it will good to update lifecycle hooks to mitigate the console warning.

![image](https://user-images.githubusercontent.com/47495003/93597378-936f0480-f9d8-11ea-9429-f0db507b05c4.png)

Awaiting your response.

**Comment by mercs600** [comment]
Thank you for tests @jd-0001 I will check it

**Comment by crutch12** [comment]
@mercs600 any progress with this?

**Comment by mercs600** [comment]
Thanks to @crutch12 we have created separate version for vue3 -> https://github.com/mercs600/vue3-perfect-scrollbar
