### ISSUE TITLE
It doesn't scroll using any external magic keyboard

### ISSUE THREAD

**Issue by Torone** [mercs600/vue2-perfect-scrollbar#67]
It work fine on desktop and any device but if I attach the magic keyboard to the iPad PRO, it doesn't scroll anymore by doing the 2 fingers gesture. It works fine on the Mac Book Pro magic keyboard.
Testing it on the Microsoft surface, same issue, it doesn't work.
There must be an event not catched.
Regards

**Comment by dzcpy** [comment]
Same problem

**Comment by dzcpy** [comment]
Any updates?

**Comment by mercs600** [comment]
Please notice this vue plugin is only wrapper for https://github.com/mdbootstrap/perfect-scrollbar/ and all question related scroll logic should be addressed  there

**Comment by dzcpy** [comment]
Changed to using Observer in GSAP and got this issue fixed.
