### ISSUE TITLE
Typescript declarations, please?

### ISSUE THREAD

**Issue by thoni56** [mercs600/vue2-perfect-scrollbar#7]
It seems there are no typescript definitions. Could you please add a `vue2-perfect-scrollbar.d.ts`?

**Comment by mercs600** [comment]
Yes I can but I have to find some time to do it ;-) Otherwise you can push some PR if you need it quickly.

**Comment by thoni56** [comment]
I know ;-) I'll see what I can do, just wanted to create this as a note.
