### ISSUE TITLE
new version 1.5.56

### ISSUE THREAD

**Issue by rr-alexander-belykh** [mercs600/vue2-perfect-scrollbar#97]
Hi @mercs600 
Is this new version "1.5.56" correct?
The previous one was "1.5.5"
Looks like should be "1.5.6" instead

**Comment by mercs600** [comment]
@rr-alexander-belykh yes it is, I want to sync version of this repo with the origin of perfect-scrollbar library -> https://github.com/mdbootstrap/perfect-scrollbar which is 1.5.5
